config/routes.rb
Rails.application.routes.draw do
  #開発環境用レターオープナーのルーティング
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  #デフォルトページのルーティング
  get '', to: 'sessions#new'

  #写真投稿機能のルーティング
  resources :posts do
    collection do
      post :confirm
    end
  end

  #お気に入り機能のルーティング
  resources :favorites, only: [:show,:create, :destroy]

  #セッション管理機能のルーティング
  resources :sessions, only: [:new, :create, :destroy]

  #ユーザー管理機能のルーティング
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  validates :image, presence: true
  validates :content, length: { in: 1..140 }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
    @favorite_posts = current_user.favorite_posts
  end

  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_url, notice: "#{favorite.post.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_url, notice: "#{favorite.post.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("id DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  # GET /posts/new
  def new
    if params[:back]
      @post = current_user.posts.build(post_params)
    else
      @post = Post.new
    end
  end

  # GET /posts/1/edit
  def edit
    unless current_user.id == @post.user_id
      flash[:notice] = "他のユーザーの投稿は編集できません"
      redirect_to posts_path and return
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      PostMailer.post_mail(@post).deliver
        flash[:notice] = "投稿が完了しました"
      redirect_to posts_path
    else
      render :new
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      flash[:notice] = "投稿が完了しました"
      redirect_to posts_path
    else
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    unless current_user.id == @post.user_id
      flash[:notice] = "他のユーザーの投稿は編集できません"
      redirect_to posts_path and return
    end
    if @post.destroy
      redirect_to posts_path, notice: "投稿の削除が完了しました"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :image, :image_cache, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ろぐあうとしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to new_session_path
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      flash[:notice] = "編集が完了しました。"
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = "編集に失敗しました。"
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :imgae_cache)
    end

    def check_login
      if logged_in?
      else
        flash[:notice] = "ログインしてください"
        redirect_to new_session_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm" || action_name == "create"
      confirm_posts_path
    elsif action_name == "edit"
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/_favorites.html.erb
<div class="post_container">
  <div class="post_header">
    <%= image_tag post.user.image.url %>
    <%= post.user.name %>
  </div>
  <div class="post_image">
    <%= image_tag post.image.url %>
  </div>
  <div class="post_text">
    <%= post.content %>
  </div>

    <div class="post_menu">
      <%= link_to '確認', post_path(post.id), class: 'btn btn-info'  %>
      <% if current_user.id == post.user_id %>
        <%= link_to '編集', edit_post_path(post), class: 'btn btn-success'  %>
        <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %>
      <% end %>

    </div>

</div>

app/views/favorites/show.html.erb
<h2>favorites#show</h2>
  <% @favorite_posts.each do |post| %>
  <%= render 'favorites', post: post %>
  <% end %>

<%= link_to 'New Post', new_post_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="header_container">
        <div class="header_left">

        </div>
        <h2>Instagram Clone</h2>
        <div class="header_right">
          <% if logged_in? %>
              <%= link_to "プロフィール", user_path(current_user.id), class: "btn btn-info btn-lg" %>
              <%= link_to "ログアウト", session_path(current_user.id), method: :delete , class: "btn btn-danger btn-lg" %>
              <%= link_to '投稿一覧', posts_path, class: "btn btn-success btn-lg"  %>
              <%= link_to '新規投稿', new_post_path, class: "btn btn-primary btn-lg"  %>
              <%= link_to 'お気に入り', favorite_path(current_user.id), class: "btn btn-primary btn-lg"  %>
          <% else %>
              <%= link_to "ユーザー登録", new_user_path, class: "btn btn-primary btn-lg"  %>
              <%= link_to "ログイン", new_session_path, class: "btn btn-primary btn-lg"  %>
          <% end %>
        </div>
      </div>
      <div class="flash_message">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form_container">
  <%= form_with(model: post, local: true, url: choose_new_or_edit) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= post.errors.count %> 件のエラーがあります。</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form_main">
      <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content %>
      </div>

      <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image %>
        <%= image_tag(post.image.url) if post.image && post.image.url %>
        <%= form.hidden_field :image_cache %>
      </div>
      <%= form.hidden_field :user_id %>
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post_container">
  <div class="post_header">
    <% if post.user.image.url %>
      <%= image_tag post.user.image.url %>
    <% else %>
      <%= image_tag '/public/no_image.jpg' %>
    <% end %>
    <%= post.user.name %>
  </div>
  <div class="post_image">
    <%= image_tag post.image.url %>
  </div>
  <div class="post_text">
    <%= post.content %>
  </div>

    <div class="post_menu">
      <% if action_name != "index" %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-warning' %>
        <% else %>
          <%= link_to 'お気に入り登録する', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% else %>
        <%= link_to '確認', post_path(post.id), class: 'btn btn-info'  %>
      <% end %>
      <% if current_user.id == post.user_id %>
        <%= link_to '編集', edit_post_path(post), class: 'btn btn-success'  %>
        <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %>
      <% end %>

    </div>

</div>

app/views/posts/confirm.html.erb
<h2>確認画面</h2>
<div class="form_container">
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this feed from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_main">
    <p>
      <%= form.label :content %>
      <%= @post.content %>
    </p>
    <p>
      <%= form.label :image %>
      <%= image_tag (@post.image.url) if @post.image && @post.image.url %>
    </p>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :user_id %>
    <%= form.hidden_field :content %>
    <%= form.submit "投稿する" %>
  <% end %>

  <%= form_with(model: @post, url: new_post_path, local: true, method: "get") do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>投稿一覧</h2>
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

app/views/users/_form.html.erb
<div class="form_container">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= user.errors.count %> 件のエラーがあります</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form_main">

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.image %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="profile_container">
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Image:</strong>
    <% if @user.image.url %>
      <%= image_tag @user.image.url %>
    <% else %>
      <%= image_tag "/public/no_image.jpg" %>
    <% end %>
  </p>

  <p>
    <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id), class: "btn btn-info" %>
  </p>
</div>